# Dynamic Configuration
http:
  routers:
    dashboard:
      entryPoints:
        - traefik
      rule: PathPrefix(`/`) || PathPrefix(`/api`) || PathPrefix(`/dashboard`)
      service: api@internal
    console:
      entryPoints:
        - web
        - websecure
      rule: PathPrefix(`/`) || PathPrefix(`/static`)
      service: console@internal
  serversTransports:
    insecureskip:
      insecureSkipVerify: true
